### ISSUE TITLE
Maybe we should add a sourcemap?

### ISSUE THREAD

**Issue by tpronk** [kurokida/jsQUEST#5]
The bundle that's compiled with rollup makes sure the library can be used in all kinds of different module systems. However, it does mean that if an error occurs, it's difficult to trace the error back to the original source code. A sourcemap could help out with this. See https://www.npmjs.com/package/rollup-plugin-sourcemaps

**Comment by kurokida** [comment]
Thank you for your suggestion.

I have very little knowledge of the sourcemap, but I created a new branch named as sourcemap_test, and tried the following command anyway.

```
npm install --save-dev @rollup/rollup-plugin-sourcemap
```

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rollup%2frollup-plugin-sourcemap - Not found
npm ERR! 404
npm ERR! 404  '@rollup/rollup-plugin-sourcemap@latest' is not in the npm registry.

I also tried the following command, but the similar error messages were returned.

```
npm install --save-dev rollup-plugin-sourcemap
```

Because I don't know much about rollup or its plugins, I probably make  a rudimentary mistake.
Could you help me if possible?

**Comment by tpronk** [comment]
Sure, let me try some stuff out. We've got a new PsychoJS release coming up (next Wednesday). After that I'm going to work a bit more on the integration of PsychoJS and jsQUEST. I'll pick this one up and also run a couple of cross-browser tests. See if everything works as expected on [this list of platforms](https://github.com/psychopy/psychojs_testing/wiki/Platform-list#all-platforms).

**Comment by kurokida** [comment]
Thank you very much for your cooperation!
Please do it at your own pace.
I will check how jsQUEST works with gorilla and lab.js.
